ExpDiff/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('processing.views',
    url(r'^$', 'home', name='home'),
    url(r'^abundancia/$', 'abundancia_form'),
    url(r'^ab2matrix/$', 'ab2matrix_form'),
    url(r'^diffexp/$', 'diffexp_form'),
    url(r'^register/$', 'register_user'),
    url(r'^login/$', 'log_in'),
    url(r'^login/auth/$', 'auth_view'),
    url(r'^logout/$', 'log_out'),
    url(r'^files/$', 'show_files'),
    url(r'^process/$', 'show_processes'),
    url(r'^files/upload/$', 'show_fileupload', name='file_upload'),
    url(r'^files/submit/$', 'filesubmit'),
    url(r'^files/success/$', 'upload_success', name='upload_success'),
    url(r'^files/delete/(\d+)/$', 'delete_file'),
    url(r'^files/edit/(\d+)/$', 'show_edit_file', name='show_edit_file'),
    url(r'^files/(?P<id_file>\d+)/$', 'download_file', name="download_file"),
    url(r'^process/show/(?P<process_id>\d+)/$', 'show_specific_process', name="show_specific_process"),
    url(r'^process/show/$', 'show_process', name='show_process'),
    url(r'^editfile/$', 'editfile'),
    url(r'^run/abundancia/$', 'run_abundancia'),
    url(r'^run/ab2matrix/$', 'run_ab2matrix'),
    url(r'^run/expdiff/$', 'run_expdiff'),
    # Examples:
    # url(r'^$', 'ExpDiff.views.home', name='home'),
    # url(r'^ExpDiff/', include('ExpDiff.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

processing/models.py
# -*- coding: utf-8 -*-
from django.db import models
import subprocess
import threading
from django.conf import settings
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.models import User
from time import sleep
from django.core.files import File as Django_File
from django.conf import settings
from random import randint
import os

# Opciones estáticas
POSIBLES_ESTADOS_PROCESOS = (
    (0, "Terminado exitosamente"),
    (1, "Terminado con errores"),
    (2, "Iniciado"),
    (3, "En espera")
)
MAPEADORES = (
    (0, "BWA"),
    (1, "Bowtie"),
)
TIPOS_MAPEO = (
    (0, "Single end"),
    (1, "Paired end")
)


class Profile(models.Model):
    user = models.OneToOneField(User)
    email = models.EmailField()
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Perfiles'

    def __unicode__(self):
        return unicode(self.email)


class File(models.Model):
    fileUpload = models.FileField()
    description = models.TextField(default="")
    profile = models.ForeignKey(Profile)
    ext = models.CharField(max_length=7)

    class Meta:
        verbose_name_plural = 'Archivos'

    def __unicode__(self):
        return u"ARCHIVO \n Location: %s \n Description: %s " % (self.fileUpload.path, self.description)


class Proceso(models.Model):

    estado = models.IntegerField(choices=POSIBLES_ESTADOS_PROCESOS, default=3)
    std_err = models.TextField(default="")
    std_out = models.TextField(default="")
    comando = models.CharField(max_length=2000, default="echo Hola mundo")
    profile = models.ForeignKey(Profile)

    class Meta:
        verbose_name_plural = 'Procesos'

    def get_estado(self):
        return POSIBLES_ESTADOS_PROCESOS[self.estado][1]

    def run_process(self):
        self.estado = 2
        self.save()
        try:
            p = subprocess.Popen(str(self.comando), stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
            self.std_out, self.std_err = p.communicate()
            self.estado = p.returncode
        except:
            try:
                self.std_out, self.std_err = p.communicate()
                self.estado = 0
                self.save()
            except:
                self.estado = 0
                self.save()
        #  self.std_out = self.std_out.replace("\n", "<br>")
        #  self.std_err = self.std_err.replace("\n", "<br>")
        self.save()

    def run(self):
        t = threading.Thread(target=self.run_process)
        t.setDaemon(True)
        t.start()

    def __unicode__(self):
        return u"ID: %s Estado: %s \n Comando: %s \n STDOUT: \n %s \n STDERR: %s\n " % (str(self.id), str(self.estado), str(self.comando), str(self.std_out), str(self.std_err))


class Align_and_estimate_abundance(models.Model):

    """"
    Run example
    type=1 -> Single end
    type=2 -> Paired end
    m = Mapeo(name="Exp", mapeador=0, tipo=1, profile=p)
    m.save()
    """
    name = models.TextField(default="Experimento")
    procesos = models.ManyToManyField(Proceso)
    mapeador = models.IntegerField(choices=MAPEADORES, default=1)
    tipo = models.IntegerField(default=1, choices=TIPOS_MAPEO)
    profile = models.ForeignKey(Profile)
    out_file = models.ForeignKey(File, null=True)

    def run_this(self, reference="", reads_1="", reads_2="", reads_se=""):
        self.name = "Experimento %s" % self.id
        self.save()
        tmp_dir = "/tmp/aln%s" % randint(1, 1000000)
        comando = "$TRINITY_HOME/util/align_and_estimate_abundance.pl --thread_count %s  --output_dir %s  --transcripts %s --left %s --right %s --seqType fq --est_method RSEM --aln_method bowtie --prep_reference" % (settings.CORES, tmp_dir, reference, " ".join(reads_1), " ".join(reads_2))
        print reads_1
        print reads_2
        p1 = Proceso(comando=str(comando), profile=self.profile)
        p1.save()
        self.procesos.add(p1)
        # To get files with path trin.fileUpload.path
        # Genero indice y espero hasta que este listo
        t1 = threading.Thread(target=p1.run_process)
        t1.setDaemon(True)
        t1.start()
        while t1.isAlive():
            sleep(1)
        file_name = "%s/RSEM.isoforms.results" % tmp_dir
        out_file = File(fileUpload=Django_File(open(file_name)), description="Salida " + self.name, profile=self.profile, ext="results")
        out_file.save()
        self.out_file = out_file

    def run(self, reference, reads_1="", reads_2=""):
        t = threading.Thread(target=self.run_this, kwargs=dict(reference=reference, reads_1=reads_1, reads_2=reads_2))
        t.setDaemon(True)
        t.start()

    class Meta:
        verbose_name_plural = "Procesos de alinear y estimar abundancia"

    def __unicode__(self):
        return u"Alineamiento y estimación \n %s" % self.name


class Abundance_to_Matrix(models.Model):
    name = models.TextField(default="Abundance_to_Matrix Results")
    procesos = models.ManyToManyField(Proceso)
    out_results = models.ForeignKey(File, null=True, related_name="file_results_Abundance_to_Matrix")
    profile = models.ForeignKey(Profile)

    def run_this(self, files=""):
        self.name = "Abundance_to_Matrix Results. Exp: %s " % self.id
        self.save()
        out_dir = "/tmp/matrix%s" % str(randint(1, 65000))
        try:
            os.mkdir(out_dir)
        except:
            pass
        prefix = "VS".join([f.split("/")[-1].replace(".results", "") for f in files])
        comando = "$TRINITY_HOME/util/abundance_estimates_to_matrix.pl --est_method RSEM  --out_prefix  %s/%s %s" % (str(out_dir), str(prefix), " ".join(files))
	print comando
        p = Proceso(comando=str(comando), profile=self.profile)
        p.save()
        self.procesos.add(p)
        t1 = threading.Thread(target=p.run_process)
        t1.setDaemon(True)
        t1.start()
        while t1.isAlive():
            sleep(1)
        f1 = File(fileUpload=Django_File(open(out_dir + "/%s.counts.matrix" % prefix)), description="Salida " + self.name, profile=self.profile, ext="matrix")
        f1.save()
        self.out_results = f1

    class Meta:
        verbose_name_plural = "Procesos de abundancia a matriz"

    def run(self, files=""):
        t = threading.Thread(target=self.run_this, kwargs=dict(files=files))  # Replace for bwa when ready
        t.setDaemon(True)
        t.run()

    def __unicode__(self):
        print name


class Differential_Expression(models.Model):
    name = models.TextField(default="Differential_Expression Results")
    procesos = models.ManyToManyField(Proceso)
    out_results = models.ForeignKey(File, null=True, related_name="file_results_Differential_Expression")
    out_params = models.ForeignKey(File, null=True, related_name="file_rparams_Differential_Expression")
    profile = models.ForeignKey(Profile)

    def run_this(self, matrix=""):
        self.name = "Differential_Expression Results. Exp: %s " % self.id
        self.save()
        out_dir = "/tmp/DE%s" % str(randint(1, 65000))
        comando = "$TRINITY_HOME/Analysis/DifferentialExpression/run_DE_analysis.pl -o  %s --matrix %s --method edgeR" % (str(out_dir), matrix)
        p = Proceso(comando=str(comando), profile=self.profile)
        p.save()
        self.procesos.add(p)
        t1 = threading.Thread(target=p.run_process)
        t1.setDaemon(True)
        t1.start()
        while t1.isAlive():
            sleep(1)
        result = subprocess.check_output("ls -1 %s/*pdf" % out_dir, shell=True)
        f1 = File(fileUpload=Django_File(open(result.strip())), description="PDF output " + self.name, profile=self.profile, ext="pdf")
        f1.save()
        self.out_results = f1
        result = subprocess.check_output("ls -1 %s/*results" % out_dir, shell=True)
        f1 = File(fileUpload=Django_File(open(result.strip())), description="Data output " + self.name, profile=self.profile, ext="csv")
        f1.save()
        self.out_params = f1
        self.save()


    class Meta:
        verbose_name_plural = "Procesos de expresion diferencial"

    def run(self, matrix=""):
        t = threading.Thread(target=self.run_this, kwargs=dict(matrix=matrix))  # Replace for bwa when ready
        t.setDaemon(True)
        t.run()

    def __unicode__(self):
        print name

processing/forms.py
from django import forms
from django.db import models


class UploadFileForm(forms.Form): 
    title = forms.CharField(max_length=50) 
    fileUploaded = forms.FileField() 
    description = models.TextField(max_length=200)

ExpDiff/templates/ab2matrix_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/abundancia/">Alinear y estimar abundancia</a></li>
            <li><a href="/ab2matrix/">Abundancias a matriz</a></li>
            <li><a href="/diffexp/">Expresión Diferencial</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Abundancia a matriz
        </h1><br><br>
        <div id='pairedform'>
            <form id='formpaired' action="/run/ab2matrix/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-10">
                            <label for="id_lreads">Archivos .result:</label>
                            <select class="form-control" id="id_result" name="result" multiple required>
                                {% for r in resultList %}
                                    <option value='{{r.id}}'>{{r.fileUpload.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-default">Enviar</button>
            </form>
        </div>
            
    </div>
</div>
{% endblock %}

ExpDiff/templates/abundancia_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/abundancia/">Alinear y estimar abundancia</a></li>
            <li><a href="/ab2matrix/">Abundancias a matriz</a></li>
            <li><a href="/diffexp/">Expresión Diferencial</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Alinear y estimar abundancia
        </h1><br><br>
        <div id='pairedform'>
            <form id='formpaired' action="/run/abundancia/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_reference">Archivo de referencia:</label>
                    <select class="form-control" id="id_reference" name="reference"  required>
                        <option value="">seleccione un archivo</option>
                        {% for f in fastaList %}
                            <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="id_lreads">Archivo de ecturas izquierdas:</label>
                            <select class="form-control" id="id_lreads" name="lreads" multiple required>
                                {% for f in fastqList %}
                                    <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-sm-6">
                            <label for="id_rreads">Archivo de lecturas derechas:</label>
                            <select class="form-control" id="id_rreads" name="rreads" multiple required>
                                {% for f in fastqList %}
                                    <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <input type='hidden' name='mapping' id='id_mapping' value='1'>
                <input type='hidden' name='type' id='id_type' value='2'>
                <button type="submit" class="btn btn-default">Enviar</button>
            </form>
        </div>
            
    </div>
</div>
{% endblock %}

ExpDiff/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="http://bioinfud.com/DifExp/bootstrap.min.css"/>
    <!-- Optional theme -->  
    
    <title>{% block title %}DifExp{% endblock %}</title>
        <!-- Latest compiled and minified JavaScript and JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
              
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <a class="navbar-brand" href="/">DifExp</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                
                    
                {% endif %}
                {% if not user.is_authenticated %}
                    <li><a href="/register/">Registrarse</a></li>
                    <li><a href="/login/">Acceder</a></li>
                {% else %}
                    <li><a href="/logout/">Salir</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li><a href="/files/">Archivos</a></li>
                    <li><a href="/process/show/">Procesos</a></li>
                {% endif %}

              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        </div>
    </div>
            {% block content %}{% endblock %}
</div>
</body>
</html>

ExpDiff/templates/bwa_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/diffexp/">Differential expression</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mapping <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="/bowtie/">Bowtie</a></li>
                <li><a href="/bwa/">BWA</a></li>
              </ul>
            </li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            BWA
        </h1>
        <br><br>
        <div class="form-group">
            <label>Files type:</label><br>
            <input type="radio" name="filetype" value="single" id='singleradio' checked> Single end<br>
            <input type="radio" name="filetype" value="paired" id='singleradio' > Paired end<br>
        </div>
        <div id='singleform' style='display:block'>
            <form id='formsingle' action="/mapping/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_reference">Reference file:</label>
                    <select class="form-control" id="id_reference" name="reference"  required>
                        <option value="">select a file</option>
                        {% for f in fastaList %}
                            <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_reads">Reads file:</label>
                    <select class="form-control" id="id_reads" name="reads" multiple required>
                        {% for f in fastqList %}
                            <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type='hidden' name='mapping' id='id_mapping' value='1'>
                <input type='hidden' name='type' id='id_type' value='1'>
                <button type="submit" class="btn btn-default">Enviar</button>
            </form>
        </div>
        <div id='pairedform' style='display:none'>
            <form id='formpaired' action="/mapping/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_reference">Reference file:</label>
                    <select class="form-control" id="id_reference" name="reference"  required>
                        <option value="">select a file</option>
                        {% for f in fastaList %}
                            <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="id_lreads">Left reads file:</label>
                            <select class="form-control" id="id_lreads" name="lreads" multiple required>
                                {% for f in fastqList %}
                                    <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-sm-6">
                            <label for="id_rreads">Right reads file:</label>
                            <select class="form-control" id="id_rreads" name="rreads" multiple required>
                                {% for f in fastqList %}
                                    <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <input type='hidden' name='mapping' id='id_mapping' value='1'>
                <input type='hidden' name='type' id='id_type' value='2'>
                <button type="submit" class="btn btn-default">Enviar</button>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
var FieldCount=0;
$("input[name=filetype]:radio").change(function () {
    if($('#singleradio').is(':checked')) {
        $('#pairedform').hide();
        $('#singleform').show();
    }else{
        $('#singleform').hide();
        $('#pairedform').show();
    }
    
});
</script>
{% endblock %}

ExpDiff/templates/delete_file_error.html
error

ExpDiff/templates/files.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/upload/">Subir archivos</a></li>
            <li><a href="/process/show/">lista de procesos</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Lista de archivos
        </h1><br><br>
        <div class="list-group">
            {% for f in file_list %}
                <div href="#" class="list-group-item glyphicon glyphicon-file">
                    <span class="" title="Description: {{f.description}}">
                        {{f.fileUpload.name|truncatechars:50}}
                    </span>
                    <span class="pull-right">
                        <span class="label label-success glyphicon glyphicon-edit" style="display: table-cell;">
                            <a style="color:white" href="/files/edit/{{f.id}}">
                            Editar
                            </a>
                        </span>
                        <span class="label label-danger glyphicon glyphicon-remove" style="display: table-cell;">
                            <a style="color:white" href="/files/delete/{{f.id}}">
                            Borrar 
                            </a>
                        </span>
                        <span class="label label-success glyphicon glyphicon-download" style="display: table-cell;">
                            <a style="color:white" href="/files/{{f.id}}/">
                            Descargar 
                            </a>
                        </span>
                        
                    </span>
                    
                </div> 
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

ExpDiff/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <form role="form" action="/login/auth/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Correo electrónico</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Acceder</button>
        </form>
        <div class="row">
            <p class="text-muted">¿no posee una cuenta?: <a href="/register/">Registrarse</a></p>
        </div>
    </div>
    <div class="col-sm-4"></div>
</div>
{% endblock %}

ExpDiff/templates/logout.html
{% extends "base.html" %}
{% block content %}
    la sesion fue cerrada: <a href="/">home</a>
{% endblock %}

ExpDiff/templates/processes.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/upload/">Subir archivo</a></li>
            <li><a href="/files/">Mis archivos</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Lista de procesos
        </h1>
        A continuacion se listan los procesos que ha corrido en el sistema
        <table class="table">
        <thead>
            <tr>
                <th>Comando</th>
                <th>Estado</th>
                <th>Ver </th>
            </tr>
        </thead>
        <tbody>
            {% for p in process_list %}
            <tr>
                <td>{{p.comando|slice:":65"}}</td>
                <td>{{p.get_estado}}</td>
                <td> <a href="/process/show/{{p.id}}/">Ver</a>

            </tr>
            {% endfor %}
        </tbody>

    </div>
</div>

{% endblock %}

ExpDiff/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <h2>Registro</h2><br>
            <form action="/register/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Correo electrónico:</label>
                    <input class="form-control" id="id_email" maxlength="75" name="email" type="email">
                </div>
                <div class="form-group">
                    <label for="id_firstName">Nombres:</label>
                    <input class="form-control" id="id_firstName" maxlength="30" name="firstName" type="text">
                </div>
                <div class="form-group">
                    <label for="id_lastName">Apellidos:</label>
                    <input class="form-control" id="id_lastName" maxlength="30" name="lastName" type="text">
                </div>
                <div class="form-group">
                    <label for="id_password1">Contraseña:</label>
                    <input class="form-control" id="id_password1" name="password1" type="password">
                </div>
                <div class="form-group">
                    <label for="id_password2">Repetir contraseña:</label>
                    <input class="form-control" id="id_password2" name="password2" type="password">
                </div>
                <button type="submit" class="btn btn-default">Registrarse</button>
            </form>
        </div>
        <div class="col-sm-3"> </div>
    </div>
    {% endblock %}

ExpDiff/templates/registration_success.html
{% extends "base.html" %}
{% block content %}
el registro fue todo un exito :D
{% endblock %}

ExpDiff/templates/show_edit_file.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/">Mis archivos</a></li>
            <li><a href="/files/upload/">Subir archivo</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        
        <h1>
            Editar archivo
        </h1>
        <form action="/editfile/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_description"><h4>Descripción:</h4></label>
                    <input class="form-control" id="id_description" name="description" type="text">
                    <input id='id_fileid' name='fileid' type='hidden' value='{{fileID}}'>
                </div>
                <button type="submit" class="btn btn-default">Editar</button>
            </form>

    </div>
</div>

{% endblock %}

ExpDiff/templates/show_processes.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/upload/">Upload file</a></li>
            <li><a href="#">Otra opcion</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Files list
        </h1>
        <div class="list-group">
            {% for f in file_list %}
                <div href="#" class="list-group-item glyphicon glyphicon-file">
                    <span class="" title="Description: {{f.description}}">
                        {{f.fileUpload.name}}
                    </span>
                    <span class="pull-right">
                        <span class="label label-success glyphicon glyphicon-edit">
                            <a style="color:white" href="/files/edit/{{f.id}}">
                            Edit
                            </a>
                        </span>
                        <span class="label label-danger glyphicon glyphicon-remove">
                            <a style="color:white" href="/files/delete/{{f.id}}">
                            Delete 
                            </a>
                        </span>
                        
                    </span>
                    
                </div> 
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

ExpDiff/templates/success.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">

    </div>
    <div class="col-sm-6">
        <div class="alert alert-success">
            Mensaje:<br><br>
            {{success}}
        </div>
    </div>
    <div class="col-sm-3">

    </div>
</div>

{% endblock %}